# Japan Cluster Configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: carbon-jp
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
  - role: worker
    labels:
      region: jp
      zone: tokyo
      carbon-aware: "true"
